apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: node-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-be
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate     
  template:
    metadata:
      labels:
        app: node-be
    spec:
      containers:
      - name: backend
        image: us.gcr.io/kubernetes-295202/fastmsg-be
        ports:
        - containerPort: 8080

